// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v5.26.1
// source: auth.proto

/* eslint-disable */

export enum LoginType {
  LOGIN_TYPE_UNKNOWN = 0,
  /** LOGIN_TYPE_GOOGLE - google */
  LOGIN_TYPE_GOOGLE = 1,
  /** LOGIN_TYPE_TWITTER - twitter */
  LOGIN_TYPE_TWITTER = 2,
  /** LOGIN_TYPE_WALLET - 钱包 */
  LOGIN_TYPE_WALLET = 3,
  UNRECOGNIZED = -1,
}

export enum LoginResFlag {
  LOGIN_SUCC = 0,
  UNRECOGNIZED = -1,
}

export interface NonceReq {}

export interface NonceRsp {
  nonce: string
}

export interface LoginReq {
  access_token: string
  secret: string
  /** 邀请码 */
  refer_code: string
  /** 钱包登录使用 */
  message: string
  signature: string
  login_type: number
}

export interface LoginRsp {
  uid: number
  token: string
  expire: number
  res_flag: number
}

export interface Auth {
  /** 生成nonce */
  Nonce(request: NonceReq): Promise<NonceRsp>
  /** 登录 */
  Login(request: LoginReq): Promise<LoginRsp>
}
